apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: bookspot
data:
  init-db.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE books_db;
    CREATE DATABASE notification_db;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bookspot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookspot-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d/init-db.sql
          subPath: init-db.sql
      volumes:
      - name: postgres-init
        configMap:
          name: postgres-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bookspot
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
