package custommodel

import (
	"time"

	"gorm.io/gorm"
)

// CustomModel is a variant of gorm.Model
// that uses uuid as a string that is generated by uuid_generate_v4() as primary key instead of uint
type CustomModel struct {
	ID        string `gorm:"type:uuid;default:uuid_generate_v4();primaryKey"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
}
